"""Add full OpenWeatherMap fields to WeatherForecast

Revision ID: 0539089229a6
Revises: 55acb65b68da
Create Date: 2026-03-05 20:30:29.958610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0539089229a6'
down_revision = '55acb65b68da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_forecast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feels_like', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pressure', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('humidity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uvi', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clouds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wind_speed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wind_deg', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pop', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_forecast', schema=None) as batch_op:
        batch_op.drop_column('pop')
        batch_op.drop_column('wind_deg')
        batch_op.drop_column('wind_speed')
        batch_op.drop_column('visibility')
        batch_op.drop_column('clouds')
        batch_op.drop_column('uvi')
        batch_op.drop_column('humidity')
        batch_op.drop_column('pressure')
        batch_op.drop_column('feels_like')

    # ### end Alembic commands ###
