"""empty message

Revision ID: 1f40b3e904f1
Revises: ea7987a3ad39
Create Date: 2026-02-04 02:00:29.624882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f40b3e904f1'
down_revision = 'ea7987a3ad39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.alter_column('banking',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否支持现场银行卡/信用卡支付；0=不支持，1=支持',
               existing_comment='是否支持现场银行卡/信用卡支付',
               existing_nullable=False)
        batch_op.alter_column('bonus',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否为奖励站点（还车可获额外时长等）；0=否，1=是',
               existing_comment='是否为奖励站点（还车可获额外时长等）',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.alter_column('bonus',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否为奖励站点（还车可获额外时长等）',
               existing_comment='是否为奖励站点（还车可获额外时长等）；0=否，1=是',
               existing_nullable=False)
        batch_op.alter_column('banking',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否支持现场银行卡/信用卡支付',
               existing_comment='是否支持现场银行卡/信用卡支付；0=不支持，1=支持',
               existing_nullable=False)

    # ### end Alembic commands ###
