"""empty message

Revision ID: 1f40b3e904f1
Revises: ea7987a3ad39
Create Date: 2026-02-04 02:00:29.624882

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1f40b3e904f1"
down_revision = "ea7987a3ad39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("station", schema=None) as batch_op:
        batch_op.alter_column(
            "banking",
            existing_type=mysql.TINYINT(display_width=1),
            comment="Whether onsite bank card/credit card payment is supported; 0=not supported, 1=supported",
            existing_comment="Whether onsite bank card/credit card payment is supported",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "bonus",
            existing_type=mysql.TINYINT(display_width=1),
            comment="Whether it is a bonus station (returning bikes can earn extra time, etc.); 0=no, 1=yes",
            existing_comment="Whether it is a bonus station (returning bikes can earn extra time, etc.)",
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("station", schema=None) as batch_op:
        batch_op.alter_column(
            "bonus",
            existing_type=mysql.TINYINT(display_width=1),
            comment="Whether it is a bonus station (returning bikes can earn extra time, etc.)",
            existing_comment="Whether it is a bonus station (returning bikes can earn extra time, etc.); 0=no, 1=yes",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "banking",
            existing_type=mysql.TINYINT(display_width=1),
            comment="Whether onsite bank card/credit card payment is supported",
            existing_comment="Whether onsite bank card/credit card payment is supported; 0=not supported, 1=supported",
            existing_nullable=False,
        )

    # ### end Alembic commands ###
