"""Add WeatherForecast Table

Revision ID: 55acb65b68da
Revises: d4e5f6a7b8c9
Create Date: 2026-03-05 20:12:51.601081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55acb65b68da'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_forecast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_time', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_forecast', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_forecast_forecast_time'), ['forecast_time'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_forecast', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_forecast_forecast_time'))

    op.drop_table('weather_forecast')
    # ### end Alembic commands ###
