"""empty message

Revision ID: 595fe8c14efb
Revises: 74b728f9c4e2
Create Date: 2026-02-02 17:36:28.755114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595fe8c14efb'
down_revision = '74b728f9c4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('contract_name', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('banking', sa.Boolean(), nullable=False),
    sa.Column('bonus', sa.Boolean(), nullable=False),
    sa.Column('bike_stands', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('available_bikes', sa.Integer(), nullable=False),
    sa.Column('available_bike_stands', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_update', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['number'], ['station.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability')
    op.drop_table('station')
    # ### end Alembic commands ###
