"""add langchain chat history table

Revision ID: ad9368933e53
Revises: d4e5f6a7b8c9
Create Date: 2026-03-08 18:36:33.693944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9368933e53'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('message', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_store')
    # ### end Alembic commands ###
