"""empty message

Revision ID: ea7987a3ad39
Revises: 595fe8c14efb
Create Date: 2026-02-04 01:58:32.096606

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ea7987a3ad39"
down_revision = "595fe8c14efb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("station", schema=None) as batch_op:
        batch_op.alter_column(
            "banking",
            existing_type=mysql.TINYINT(display_width=1),
            comment="Whether onsite bank card/credit card payment is supported",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "bonus",
            existing_type=mysql.TINYINT(display_width=1),
            comment="Whether it is a bonus station (returning bikes can earn extra time, etc.)",
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("station", schema=None) as batch_op:
        batch_op.alter_column(
            "bonus",
            existing_type=mysql.TINYINT(display_width=1),
            comment=None,
            existing_comment="Whether it is a bonus station (returning bikes can earn extra time, etc.)",
            existing_nullable=False,
        )
        batch_op.alter_column(
            "banking",
            existing_type=mysql.TINYINT(display_width=1),
            comment=None,
            existing_comment="Whether onsite bank card/credit card payment is supported",
            existing_nullable=False,
        )

    # ### end Alembic commands ###
